import { formatDate } from '../../utils/formatDate';
import { ArchiveIcon, SpamIcon, InboxIcon, ArrowLeftIcon } from '../UI/Icons';

export default function PreviewPanel({ email, onMoveFolder, onBack }) {
  if (!email) {
    return (
      <div className="preview-panel">
        <div className="preview-empty">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <rect x="2" y="4" width="20" height="16" rx="2" />
            <path d="m22 7-10 7L2 7" />
          </svg>
          <p>Select an email to read</p>
        </div>
      </div>
    );
  }

  return (
    <div className="preview-panel open">
      <button className="preview-back" onClick={onBack}>
        <ArrowLeftIcon /> Back
      </button>
      <div className="preview-header">
        <div className="preview-subject">{email.subject}</div>
        <div className="preview-meta">
          <span className="preview-sender">{email.senderName}</span>
          <span className="preview-meta-secondary">
            {formatDate(email.timestamp)}
          </span>
        </div>
      </div>
      <div className="preview-body">{email.body}</div>
      <div className="generated-notice">Generated by AI for entertainment purposes.</div>
      <div className="preview-footer">
        {email.folder === 'inbox' && (
          <>
            <button className="btn btn-ghost btn-sm" onClick={() => onMoveFolder(email._id, 'archive')}>
              <ArchiveIcon /> Archive
            </button>
            <button className="btn btn-danger btn-sm" onClick={() => onMoveFolder(email._id, 'spam')}>
              <SpamIcon /> Spam
            </button>
          </>
        )}
        {email.folder === 'archive' && (
          <button className="btn btn-ghost btn-sm" onClick={() => onMoveFolder(email._id, 'inbox')}>
            <InboxIcon /> Move to Inbox
          </button>
        )}
        {email.folder === 'spam' && (
          <button className="btn btn-ghost btn-sm" onClick={() => onMoveFolder(email._id, 'inbox')}>
            <InboxIcon /> Not Spam
          </button>
        )}
      </div>
    </div>
  );
}
