import { getModel } from '../config/gemini.js';
import Sender from '../models/Sender.js';
import Email from '../models/Email.js';

const TOPICS = [
  'a product launch announcement',
  'an internal strategy update',
  'a media response to recent news',
  'an investor communication',
  'an event invitation',
  'a partnership proposal',
  'a quarterly performance review',
  'a team restructuring announcement',
  'a personal reflection on industry trends',
  'a proposal for a new initiative',
];

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function buildPrompt(sender) {
  const topic = pickRandom(TOPICS);
  return `You are ${sender.name}, a ${sender.archetype}. 

Your writing style: ${sender.writingStylePrompt}

Write a brief executive email (2-4 paragraphs) to a colleague regarding ${topic}. 
The email should feel like a realistic, high-level business communication. 
Be specific and detailed — include plausible names, numbers, dates, or products where relevant.

End the email EXACTLY with this line (no variations):
"Generated by AI for entertainment purposes."

Do not include a subject line in the body. The response should be the body only.`;
}

export async function generateEmailsForUser(userId, count = 2) {
  const senders = await Sender.aggregate([{ $sample: { size: count } }]);
  if (!senders.length) return [];

  const model = getModel();
  const results = [];

  for (const sender of senders) {
    try {
      const prompt = buildPrompt(sender);
      const topic = pickRandom(TOPICS);

      let subjectTopic;
      if (topic.includes('product launch')) subjectTopic = 'New Product Launch';
      else if (topic.includes('strategy update')) subjectTopic = 'Strategic Update';
      else if (topic.includes('media response')) subjectTopic = 'Media Statement';
      else if (topic.includes('investor communication')) subjectTopic = 'Investor Update';
      else if (topic.includes('event invitation')) subjectTopic = 'Event Invitation';
      else if (topic.includes('partnership proposal')) subjectTopic = 'Partnership Opportunity';
      else if (topic.includes('quarterly')) subjectTopic = 'Quarterly Review';
      else if (topic.includes('restructuring')) subjectTopic = 'Team Update';
      else if (topic.includes('personal reflection')) subjectTopic = 'Industry Thoughts';
      else subjectTopic = 'New Initiative';

      const subject = `Re: ${subjectTopic}`;

      const result = await model.generateContent(prompt);
      const body = result.response.text().trim();

      const email = await Email.create({
        userId,
        senderName: sender.name,
        subject,
        body,
        category: sender.category,
        folder: 'inbox',
      });

      results.push(email);
    } catch (err) {
      console.error(`Gemini generation error for ${sender.name}:`, err.message);
    }
  }

  return results;
}
