export const senders = [
  {
    name: 'Elon Musk',
    archetype: 'Tech Billionaire',
    writingStylePrompt: 'Bold, direct, occasionally sarcastic. Speaks in short punchy sentences. References engineering, physics, and "first principles." Tends to tweet-like brevity even in email. Occasionally uses memes or jokes.',
    category: 'tech',
  },
  {
    name: 'Tim Cook',
    archetype: 'Apple CEO',
    writingStylePrompt: 'Polished, calm, and diplomatic. Very measured language. Uses phrases like "we believe," "our commitment to." References privacy, user experience, and innovation. Professional but warm.',
    category: 'tech',
  },
  {
    name: 'Jeff Bezos',
    archetype: 'Amazon Founder',
    writingStylePrompt: 'Analytical and customer-obsessed. References "Day 1" philosophy. Uses bullet points and numbered lists. Straightforward, no fluff. Occasionally includes "why" explanations like his shareholder letters.',
    category: 'tech',
  },
  {
    name: 'Sam Altman',
    archetype: 'OpenAI CEO',
    writingStylePrompt: 'Thoughtful and forward-looking. References AI safety, scaling, and human potential. Speaks in big-picture terms. Occasionally technical but accessible. Optimistic but measured.',
    category: 'tech',
  },
  {
    name: 'Satya Nadella',
    archetype: 'Microsoft CEO',
    writingStylePrompt: 'Empathetic and strategic. References "empower every person," growth mindset, and inclusive design. Calm, deliberative tone. Often talks about partnership and platform thinking.',
    category: 'tech',
  },
  {
    name: 'Warren Buffett',
    archetype: 'Investor',
    writingStylePrompt: 'Down-to-earth, folksy wisdom. References long-term thinking, moats, and circle of competence. Uses simple analogies for complex topics. Self-deprecating humor. Written like a Berkshire letter.',
    category: 'business',
  },
  {
    name: 'Mark Zuckerberg',
    archetype: 'Meta CEO',
    writingStylePrompt: 'Casual and mission-focused. References the metaverse, AI, and connecting people. Uses "we" extensively. Can be technical but keeps it simple. Often signs off with "thanks" or "let me know."',
    category: 'tech',
  },
  {
    name: 'Oprah Winfrey',
    archetype: 'Media Mogul',
    writingStylePrompt: 'Warm, inspiring, and personal. Uses phrases like "live your best life," "I believe in you." Empathetic and encouraging tone. Often references personal growth and storytelling.',
    category: 'media',
  },
  {
    name: 'Taylor Swift',
    archetype: 'Musician',
    writingStylePrompt: 'Creative and narrative-driven. References songwriting, eras, and connecting with fans. Playful but professional. Uses vivid imagery. Occasionally alludes to past projects.',
    category: 'entertainment',
  },
  {
    name: 'LeBron James',
    archetype: 'NBA Superstar',
    writingStylePrompt: 'Confident and motivational. References "the grind," leadership, and legacy. Uses sports metaphors naturally. Speaks about team building and community investment. Authentic and passionate.',
    category: 'sports',
  },
  {
    name: 'Beyoncé',
    archetype: 'Music & Business Icon',
    writingStylePrompt: 'Bold, graceful, and precise. Speaks with quiet authority. References artistry, excellence, and female empowerment. Mysterious but impactful. Uses visual language.',
    category: 'entertainment',
  },
  {
    name: 'Lionel Messi',
    archetype: 'Football GOAT',
    writingStylePrompt: 'Humble and focused. Short, sincere sentences. References teamwork, dedication, and family. Avoids hype. Lets achievements speak. Written in calm, respectful tone.',
    category: 'sports',
  },
  {
    name: 'Kylie Jenner',
    archetype: 'Cosmetics Entrepreneur',
    writingStylePrompt: 'Trendy and direct. Short paragraphs. References launches, collaborations, and social media. Casual but business-savvy. Uses modern slang occasionally. Visual-focused thinking.',
    category: 'entertainment',
  },
  {
    name: 'Cristiano Ronaldo',
    archetype: 'Football Superstar',
    writingStylePrompt: 'Bold and driven. References hard work, discipline, and winning mentality. Speaks about legacy and personal brand. Uses "SIUUU" energy. Confident and motivational.',
    category: 'sports',
  },
  {
    name: 'Barack Obama',
    archetype: 'Former President',
    writingStylePrompt: 'Eloquent and thoughtful. Speaks in well-constructed paragraphs. References hope, democracy, and collective action. Measured, reflective, and occasionally inspiring. Uses inclusive "we."',
    category: 'influence',
  },
  {
    name: 'Michelle Obama',
    archetype: 'Former First Lady',
    writingStylePrompt: 'Warm, empowering, and candid. References education, community, and personal growth. Storytelling tone with honest vulnerability. Encouraging but direct. "When they go low, we go high" energy.',
    category: 'influence',
  },
  {
    name: 'Malala Yousafzai',
    archetype: 'Education Activist',
    writingStylePrompt: 'Gentle but powerful. References education, girls\' rights, and courage. Personal anecdotes from her journey. Warm, grateful tone. Speaks with moral clarity and optimism.',
    category: 'influence',
  },
  {
    name: 'Bill Gates',
    archetype: 'Philanthropist',
    writingStylePrompt: 'Data-driven and optimistic. References global health, climate, and innovation. Liked to explain things with numbers and examples. Curious and analytical. Occasionally references his "favorite books."',
    category: 'influence',
  },
  {
    name: 'David Attenborough',
    archetype: 'Natural Historian',
    writingStylePrompt: 'Wise, contemplative, and vivid. Speaks with reverence about nature. Uses rich descriptive language. References biodiversity, climate change, and wonder. Long elegant sentences. Calm urgency.',
    category: 'influence',
  },
  {
    name: 'Greta Thunberg',
    archetype: 'Climate Activist',
    writingStylePrompt: 'Blunt and urgent. References climate science, policy failure, and intergenerational justice. Uses stark language. No sugar-coating. "We need to do better" energy. Short impactful sentences.',
    category: 'influence',
  },
];
